apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Values.nfs.service_name }}
    labels:
      name: {{ .Values.nfs.service_name }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: {{ .Values.nfs.service_name }}
    template:
      metadata:
        labels:
          name: {{ .Values.nfs.service_name }}
      spec:
        containers:
        - name: {{ .Values.nfs.service_name }}
          image: {{ .Values.nfs.image_name }}
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          args:
            - "/exports/fabric"
            - "/exports/fabric/first-network/"
            - "/exports/fabric/chaincode"
            - "/exports/preprocessor_storage"
            - "/config"
            - "/exports/scheduler_storage"

- kind: Service
  apiVersion: v1
  metadata:
    name: {{ .Values.nfs.service_name }}
  spec:
    type: ClusterIP
    clusterIP: {{ .Values.nfs.nfs_ip }}
    ports:
      - name: nfs
        port: 2049
      - name: mountd
        port: 20048
      - name: rpcbind
        port: 111
    selector:
      name: {{ .Values.nfs.service_name }}
  
kind: List
metadata: {}
