
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.kafka.service_name }}-headless
    labels:
      app: {{ .Values.kafka.service_name }}
  spec:
    ports:
      - port: 9092
        name: broker
    clusterIP: None
    selector:
      app: {{ .Values.kafka.service_name }}

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.kafka.service_name }}
    labels:
      app: {{ .Values.kafka.service_name }}
  spec:
    type: ClusterIP
    ports:
      - port: 9092
        name: broker
    selector:
      app: {{ .Values.kafka.service_name }}



- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: {{ .Values.kafka.service_name }}
    labels:
      app: {{ .Values.kafka.service_name }}
  spec:
    selector:
      matchLabels:
        app: {{ .Values.kafka.service_name }}
    serviceName: {{ .Values.kafka.service_name }}-headless
    podManagementPolicy: OrderedReady
    replicas: 3
    template:
      metadata:
        labels:
          app: {{ .Values.kafka.service_name }}
      spec:
        containers:
          - name: {{ .Values.kafka.service_name }}
            image: {{ .Values.kafka.image_name }}
            securityContext:
              runAsUser: 0
            ports:
              - containerPort: 9092
                name: kafka
            env:
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: KAFKA_HEAP_OPTS
                value: -Xms512M -Xmx512M
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: "{{ .Values.zookeeper.service_name }}-headless:2181"
              - name: KAFKA_LOG_DIRS
                value: "/opt/kafka/data-0/logs"
              - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
                value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
              - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
                value: "3"
            command:
              - sh
              - -exc
              - |
                export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
                export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_NAME}.{{ .Values.kafka.service_name }}-headless.${POD_NAMESPACE}:9092 && \
                exec /etc/confluent/docker/run



kind: List
metadata: {}