#!/bin/sh

set -euo pipefail

LOG="/tmp/release_$$.log"
echo "********************* RELEASE *********************" >> $LOG

BLD="$1"
RELEASE="$2"

echo "BLD: $BLD" >> $LOG 2>&1
echo "RELEASE: $RELEASE" >> $LOG 2>&1

echo -en "\n\nEnvironment variables list:\n" >> $LOG
echo "---------------------------" >> $LOG
printenv >> $LOG 2>&1

if [ -d "$BLD/metadata" ]; then
   cp -a "$BLD/metadata/"* "$RELEASE/"
fi

#external chaincodes expect artifacts to be placed under "$RELEASE"/chaincode/server
if [ -f $BLD/connection.json ]; then
   mkdir -p "$RELEASE"/chaincode/server

   #if tls_required is true, copy TLS files (using above example, the fully qualified path for these fils would be "$RELEASE"/chaincode/server/tls)

   exit 0
fi

exit 1
