apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: {{ .Values.cli.service_name }}
    name: {{ .Values.cli.service_name }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: {{ .Values.cli.service_name }}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: {{ .Values.cli.service_name }}
      spec:
        containers:
        - args:
          - /bin/bash
          env: 
          {{- with .Values.cli }}
          - name: CORE_PEER_ADDRESS
            value: {{ .core_peer_address }}
          - name: CORE_PEER_ID
            value: {{ .core_peer_id }}
          - name: CORE_PEER_LOCALMSPID
            value: {{ .core_peer_localmspid }}
          - name: CORE_PEER_MSPCONFIGPATH
            value: {{ .core_peer_mspconfigpath }}
          - name: CORE_PEER_TLS_CERT_FILE
            value: {{ .core_peer_tls_cert_file }}
          - name: CORE_PEER_TLS_ENABLED
            value: {{ .core_peer_tls_enabled | quote}}
          - name: CORE_PEER_TLS_KEY_FILE
            value: {{ .core_peer_tls_key_file }}
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: {{ .core_peer_tls_rootcert_file }}
          - name: FABRIC_LOGGING_SPEC
            value: {{ $.Values.fabric.fabric_logging_spec }}
          - name: GOPATH
            value: {{ .gopath }}
          {{- end }}
          image: {{ .Values.cli.image_name }}
          name: {{ .Values.cli.service_name }}
          stdin: true
          tty: true
          volumeMounts:
          - mountPath: /fabric
            name: fabric
          workingDir: /scripts
        restartPolicy: Always
        volumes:
        - persistentVolumeClaim:
            claimName: fabric-pvc
          name: fabric
          

kind: List
metadata: {}

