
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.service_account.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service_account.name }}
    namespace: {{ .Values.service_account.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
